/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;
import javax.swing.SwingConstants;

import org.kordamp.ikonli.entypo.Entypo;
import org.kordamp.ikonli.fontawesome5.FontAwesomeSolid;
import org.kordamp.ikonli.swing.FontIcon;

import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import RSMaterialComponent.RSButtonIconOne;
import rojeru_san.efectos.ValoresEnum.ICONS;
import RSMaterialComponent.RSButtonIconTwo;

import java.awt.Color;
import java.awt.Font;
import necesario.Global.THEMETOOLTIP;
import RSMaterialComponent.RSButtonShapeIcon;
import RSMaterialComponent.RSButtonShapeIcon.FORMA;
import Vista.MainMenu;
import RSMaterialComponent.RSButtonShape;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import RSMaterialComponent.RSTextFieldTwo;
import newscomponents.RSDateChooser;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import RSMaterialComponent.RSTextFieldOne;
import java.awt.SystemColor;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import rojeru_san.complementos.RSCustomPopuMenu;
import RSMaterialComponent.RSComboBox;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author RavenPC
 */
public class ModificarEmpTurismo extends javax.swing.JPanel {

	private static final String EMAIL_PATTERN = 
		    "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
		    + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";

	DocumentFilter filter = new UppercaseDocumentFilter();
	
    /**
     * Creates new form Panel1
     */
    public ModificarEmpTurismo() {
    	setBackground(new Color(255, 255, 255));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel1.setBounds(0, 0, 785, 37);
        jLabel1.setForeground(new Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(SwingConstants.CENTER);

        jLabel1.setBackground(new Color(0, 80, 112));
        jLabel1.setFont(new Font("Dubai", Font.BOLD, 20)); // NOI18N
        jLabel1.setText("Modificar una Empresa de Turismo");
        jLabel1.setOpaque(true);
        
        RSButtonShape btnshpAgregarCliente = new RSButtonShape();
        btnshpAgregarCliente.addActionListener(new ActionListener() {
        	@Override
        	public void actionPerformed(ActionEvent e) {
        		JOptionPane.showMessageDialog(null, "LA EMPRESA DE TURISMO FUE ACTUALIZADA EXITOSAMENTE", "MENSAJE", JOptionPane.INFORMATION_MESSAGE);      	
        		//MensajeOK mensaje = new MensajeOK("GUARDAR CLIENTE", "EL CLIENTE FUE GUARDADO EXITOSAMENTE");
        		//mensaje.setVisible(true);
            	MainMenu.panelBody.removeAll();
            	MainMenu.panelBody.add(new MenuClientes());
            	MainMenu.panelBody.repaint();
            	MainMenu.panelBody.revalidate();
        	
        	}
        });
        btnshpAgregarCliente.setBounds(292, 372, 211, 63);
        btnshpAgregarCliente.setFont(new Font("Dubai", Font.BOLD, 13));
        btnshpAgregarCliente.setForegroundHover(Color.white);
        btnshpAgregarCliente.backgroundHover = UIManager.getColor("Button.shadow");
        btnshpAgregarCliente.setBackgroundHover(new Color(3, 33, 57));
        btnshpAgregarCliente.setForegroundText(Color.white);
        btnshpAgregarCliente.setForeground(Color.gray);
        btnshpAgregarCliente.setBackground(new Color(0, 51, 102));
        btnshpAgregarCliente.setHorizontalAlignment(SwingConstants.CENTER);
        btnshpAgregarCliente.setText("   GUARDAR");
        btnshpAgregarCliente.setIcon(FontIcon.of(FontAwesomeSolid.SAVE, 40, Color.white));
        btnshpAgregarCliente.setForma(RSButtonShape.FORMA.ROUND);
        
        RSButtonShape btnshpBuscarCliente = new RSButtonShape();
        btnshpBuscarCliente.addActionListener(new ActionListener() {
        	@Override
        	public void actionPerformed(ActionEvent e) {
            	MainMenu.panelBody.removeAll();
            	MainMenu.panelBody.add(new MenuClientes());
            	MainMenu.panelBody.repaint();
            	MainMenu.panelBody.revalidate();
        	}
        });
        btnshpBuscarCliente.setBounds(517, 372, 211, 63);
        btnshpBuscarCliente.setFont(new Font("Dubai", Font.BOLD, 13));
        btnshpBuscarCliente.setForegroundHover(new Color(3, 33, 57));
        btnshpBuscarCliente.setBackgroundHover(new Color(128, 128, 128));
        btnshpBuscarCliente.setForegroundText(new Color(3, 33, 57));
        btnshpBuscarCliente.setForeground(new Color(0, 128, 128));
        btnshpBuscarCliente.setBackground(new Color(211, 211, 211));
        btnshpBuscarCliente.setText("   CANCELAR");
        btnshpBuscarCliente.setHorizontalAlignment(SwingConstants.CENTER);
        btnshpBuscarCliente.setIcon(FontIcon.of(Entypo.BLOCK, 40, new Color(0, 51, 102)));
        btnshpBuscarCliente.setForma(RSButtonShape.FORMA.ROUND);
        
        JLabel lblNombre = new JLabel("Nombre  de la Empresa:");
        lblNombre.setForeground(new Color(3, 33,  57));
        lblNombre.setBounds(0, 125, 240, 33);
        lblNombre.setHorizontalAlignment(SwingConstants.RIGHT);
        lblNombre.setFont(new Font("Dubai", Font.BOLD, 20));
        setLayout(null);
        add(jLabel1);
        add(btnshpAgregarCliente);
        add(btnshpBuscarCliente);
        add(lblNombre);
        
        JLabel lblApellidoPaterno = new JLabel("Nombre del Contacto:");
        lblApellidoPaterno.setForeground(new Color(3, 33,  57));
        lblApellidoPaterno.setHorizontalAlignment(SwingConstants.RIGHT);
        lblApellidoPaterno.setFont(new Font("Dubai", Font.BOLD, 20));
        lblApellidoPaterno.setBounds(10, 178, 230, 33);
        add(lblApellidoPaterno);
        
        JLabel lblFechaDeNacimiento = new JLabel("Disponible desde:");
        lblFechaDeNacimiento.setForeground(new Color(3, 33,  57));
        lblFechaDeNacimiento.setHorizontalAlignment(SwingConstants.RIGHT);
        lblFechaDeNacimiento.setFont(new Font("Dubai", Font.BOLD, 20));
        lblFechaDeNacimiento.setBounds(54, 279, 186, 33);
        add(lblFechaDeNacimiento);
        
        RSDateChooser dateChooser = new RSDateChooser();
        dateChooser.setForeground(new Color(25, 25, 112));
        dateChooser.setBgColor(new Color(3, 33, 57));
        dateChooser.setBackground(new Color(3, 33, 57));
        dateChooser.setFormatDate("dd/MM/yyyy");
        dateChooser.setBounds(264, 270, 166, 42);
        add(dateChooser);
        
        RSTextFieldOne txtNombre = new RSTextFieldOne();
        txtNombre.addKeyListener(new KeyAdapter() {
        	@Override
        	public void keyTyped(KeyEvent evt) {
        		char c=evt.getKeyChar();
        	    if(!(Character.isAlphabetic(c) ||  (c==KeyEvent.VK_BACK_SPACE) ||  c==KeyEvent.VK_DELETE || c==KeyEvent.VK_SPACE)) {
        	    	getToolkit().beep();
        	        evt.consume();	
        	    }

        	}
        });
        txtNombre.setPlaceholder("");
        txtNombre.setPhColor(SystemColor.controlDkShadow);
        txtNombre.setForeground(new Color(25, 25, 112));
        txtNombre.setFont(new Font("Dubai", Font.BOLD, 20));
        txtNombre.setBorderColor(new Color(3, 33,  57));
        txtNombre.setBounds(264, 121, 278, 42);
        ((AbstractDocument) txtNombre.getDocument()).setDocumentFilter(filter);
        add(txtNombre);
        
        RSTextFieldOne txtApePaterno = new RSTextFieldOne();
        txtApePaterno.addKeyListener(new KeyAdapter() {
        	@Override
        	public void keyTyped(KeyEvent evt) {
        		char c=evt.getKeyChar();
        	    if(!(Character.isAlphabetic(c) ||  (c==KeyEvent.VK_BACK_SPACE) ||  c==KeyEvent.VK_DELETE || c==KeyEvent.VK_SPACE)) {
        	    	getToolkit().beep();
        	        evt.consume();	
        	    }

        	}
        });
        txtApePaterno.setPlaceholder("");
        txtApePaterno.setPhColor(SystemColor.controlDkShadow);
        txtApePaterno.setForeground(new Color(25, 25, 112));
        txtApePaterno.setFont(new Font("Dubai", Font.BOLD, 20));
        txtApePaterno.setBorderColor(new Color(3, 33,  57));
        txtApePaterno.setBounds(264, 174, 278, 42);
        ((AbstractDocument) txtApePaterno.getDocument()).setDocumentFilter(filter);
        add(txtApePaterno);
        
        JLabel lblComuna = new JLabel("Comuna donde Trabaja:");
        lblComuna.setHorizontalAlignment(SwingConstants.RIGHT);
        lblComuna.setForeground(new Color(3, 33, 57));
        lblComuna.setFont(new Font("Dubai", Font.BOLD, 20));
        lblComuna.setBounds(20, 226, 230, 33);
        add(lblComuna);
        
        RSComboBox comboBox_1 = new RSComboBox();
        comboBox_1.setModel(new DefaultComboBoxModel(new String[] {"SANTIAGO", "VALDIVIA", "VI\u00D1A DEL MAR"}));
        comboBox_1.setForeground(new Color(25, 25, 112));
        comboBox_1.setFont(new Font("Dubai", Font.BOLD, 16));
        comboBox_1.setConBorde(true);
        comboBox_1.setColorSeleccion(new Color(25, 25, 112));
        comboBox_1.setColorFondo(Color.WHITE);
        comboBox_1.setColorBorde(new Color(3, 33, 57));
        comboBox_1.setColorArrow(new Color(25, 25, 112));
        comboBox_1.setBounds(264, 227, 200, 32);
        add(comboBox_1);
        
        JLabel lblIdEmpresa = new JLabel("ID Empresa:");
        lblIdEmpresa.setHorizontalAlignment(SwingConstants.RIGHT);
        lblIdEmpresa.setForeground(new Color(3, 33, 57));
        lblIdEmpresa.setFont(new Font("Dubai", Font.BOLD, 20));
        lblIdEmpresa.setBounds(0, 72, 240, 33);
        add(lblIdEmpresa);
        
        JLabel lblIDEmpresa = new JLabel("00000002");
        lblIDEmpresa.setHorizontalAlignment(SwingConstants.LEFT);
        lblIDEmpresa.setForeground(new Color(3, 33, 57));
        lblIDEmpresa.setFont(new Font("Dubai", Font.BOLD, 20));
        lblIDEmpresa.setBounds(264, 72, 240, 33);
        add(lblIDEmpresa);
    }// </editor-fold>//GEN-END:initComponents
    private javax.swing.JLabel jLabel1;
    
    class UppercaseDocumentFilter extends DocumentFilter {
        public void insertString(DocumentFilter.FilterBypass fb, int offset,
                String text, AttributeSet attr) throws BadLocationException {

            fb.insertString(offset, text.toUpperCase(), attr);
        }

        public void replace(DocumentFilter.FilterBypass fb, int offset, int length,
                String text, AttributeSet attrs) throws BadLocationException {

            fb.replace(offset, length, text.toUpperCase(), attrs);
        }
    }
}
