/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;
import javax.swing.SwingConstants;

import org.kordamp.ikonli.entypo.Entypo;
import org.kordamp.ikonli.fontawesome5.FontAwesomeSolid;
import org.kordamp.ikonli.swing.FontIcon;

import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import RSMaterialComponent.RSButtonIconOne;
import rojeru_san.efectos.ValoresEnum.ICONS;
import RSMaterialComponent.RSButtonIconTwo;

import java.awt.Color;
import java.awt.Font;
import necesario.Global.THEMETOOLTIP;
import RSMaterialComponent.RSButtonShapeIcon;
import RSMaterialComponent.RSButtonShapeIcon.FORMA;
import Vista.MainMenu;
import RSMaterialComponent.RSButtonShape;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import RSMaterialComponent.RSTextFieldTwo;
import newscomponents.RSDateChooser;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import RSMaterialComponent.RSTextFieldOne;
import java.awt.SystemColor;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import rojeru_san.complementos.RSCustomPopuMenu;
import RSMaterialComponent.RSComboBox;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author RavenPC
 */
public class RegistroPago extends javax.swing.JPanel {

	private static final String EMAIL_PATTERN = 
		    "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
		    + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";

	DocumentFilter filter = new UppercaseDocumentFilter();
	
    /**
     * Creates new form Panel1
     */
    public RegistroPago() {
    	setBackground(new Color(255, 255, 255));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel1.setBounds(0, 0, 785, 37);
        jLabel1.setForeground(new Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(SwingConstants.CENTER);

        jLabel1.setBackground(new Color(0, 80, 112));
        jLabel1.setFont(new Font("Dubai", Font.BOLD, 20)); // NOI18N
        jLabel1.setText("Registrar un Pago de Reserva");
        jLabel1.setOpaque(true);
        
        RSButtonShape btnshpAgregarCliente = new RSButtonShape();
        btnshpAgregarCliente.addActionListener(new ActionListener() {
        	@Override
        	public void actionPerformed(ActionEvent e) {
        		JOptionPane.showMessageDialog(null, "EL CLIENTE FUE GUARDADO EXITOSAMENTE", "MENSAJE", JOptionPane.INFORMATION_MESSAGE);      	
        		//MensajeOK mensaje = new MensajeOK("GUARDAR CLIENTE", "EL CLIENTE FUE GUARDADO EXITOSAMENTE");
        		//mensaje.setVisible(true);
            	MainMenu.panelBody.removeAll();
            	MainMenu.panelBody.add(new MenuClientes());
            	MainMenu.panelBody.repaint();
            	MainMenu.panelBody.revalidate();
        	
        	}
        });
        btnshpAgregarCliente.setBounds(295, 319, 211, 63);
        btnshpAgregarCliente.setFont(new Font("Dubai", Font.BOLD, 13));
        btnshpAgregarCliente.setForegroundHover(Color.white);
        btnshpAgregarCliente.backgroundHover = UIManager.getColor("Button.shadow");
        btnshpAgregarCliente.setBackgroundHover(new Color(3, 33, 57));
        btnshpAgregarCliente.setForegroundText(Color.white);
        btnshpAgregarCliente.setForeground(Color.gray);
        btnshpAgregarCliente.setBackground(new Color(0, 51, 102));
        btnshpAgregarCliente.setHorizontalAlignment(SwingConstants.CENTER);
        btnshpAgregarCliente.setText("   REGISTRAR PAGO");
        btnshpAgregarCliente.setIcon(FontIcon.of(FontAwesomeSolid.SAVE, 40, Color.white));
        btnshpAgregarCliente.setForma(RSButtonShape.FORMA.ROUND);
        
        RSButtonShape btnshpBuscarCliente = new RSButtonShape();
        btnshpBuscarCliente.addActionListener(new ActionListener() {
        	@Override
        	public void actionPerformed(ActionEvent e) {
            	MainMenu.panelBody.removeAll();
            	MainMenu.panelBody.add(new MenuClientes());
            	MainMenu.panelBody.repaint();
            	MainMenu.panelBody.revalidate();
        	}
        });
        btnshpBuscarCliente.setBounds(520, 319, 211, 63);
        btnshpBuscarCliente.setFont(new Font("Dubai", Font.BOLD, 13));
        btnshpBuscarCliente.setForegroundHover(new Color(3, 33, 57));
        btnshpBuscarCliente.setBackgroundHover(new Color(128, 128, 128));
        btnshpBuscarCliente.setForegroundText(new Color(3, 33, 57));
        btnshpBuscarCliente.setForeground(new Color(0, 128, 128));
        btnshpBuscarCliente.setBackground(new Color(211, 211, 211));
        btnshpBuscarCliente.setText("   CANCELAR");
        btnshpBuscarCliente.setHorizontalAlignment(SwingConstants.CENTER);
        btnshpBuscarCliente.setIcon(FontIcon.of(Entypo.BLOCK, 40, new Color(0, 51, 102)));
        btnshpBuscarCliente.setForma(RSButtonShape.FORMA.ROUND);
        
        JLabel lblRUT = new JLabel("ID de Reserva:");
        lblRUT.setForeground(new Color(3, 33,  57));
        lblRUT.setBounds(12, 63, 176, 33);
        lblRUT.setHorizontalAlignment(SwingConstants.RIGHT);
        lblRUT.setFont(new Font("Dubai", Font.BOLD, 20));
        
        JLabel lblForma = new JLabel("Forma de Pago:");
        lblForma.setForeground(new Color(3, 33,  57));
        lblForma.setBounds(2, 110, 186, 33);
        lblForma.setHorizontalAlignment(SwingConstants.RIGHT);
        lblForma.setFont(new Font("Dubai", Font.BOLD, 20));
        setLayout(null);
        add(jLabel1);
        add(btnshpAgregarCliente);
        add(btnshpBuscarCliente);
        add(lblRUT);
        add(lblForma);
        
        JLabel lblApellidoPaterno = new JLabel("Monto:");
        lblApellidoPaterno.setForeground(new Color(3, 33,  57));
        lblApellidoPaterno.setHorizontalAlignment(SwingConstants.RIGHT);
        lblApellidoPaterno.setFont(new Font("Dubai", Font.BOLD, 20));
        lblApellidoPaterno.setBounds(2, 163, 186, 33);
        add(lblApellidoPaterno);
        
        JLabel lblApellidoAterno = new JLabel("N\u00B0 de Transacci\u00F3n:");
        lblApellidoAterno.setForeground(new Color(3, 33,  57));
        lblApellidoAterno.setHorizontalAlignment(SwingConstants.RIGHT);
        lblApellidoAterno.setFont(new Font("Dubai", Font.BOLD, 20));
        lblApellidoAterno.setBounds(2, 216, 186, 33);
        add(lblApellidoAterno);
        
        RSTextFieldOne txtIDReserva = new RSTextFieldOne();
        txtIDReserva.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
              char c = e.getKeyChar();
              if (!((c >= '0') && (c <= '9') ||
                 (c == KeyEvent.VK_BACK_SPACE) ||
                 (c == KeyEvent.VK_DELETE))) {
                getToolkit().beep();
                e.consume();
              }
              boolean max = txtIDReserva.getText().length() >= 9;
              if ( max ){
                  e.consume();
              }   
            }
          });
        txtIDReserva.setPlaceholder("0000001");
        txtIDReserva.setPhColor(SystemColor.controlDkShadow);
        txtIDReserva.setForeground(new Color(25, 25, 112));
        txtIDReserva.setFont(new Font("Dubai", Font.BOLD, 20));
        txtIDReserva.setBorderColor(new Color(3, 33, 57));
        txtIDReserva.setBounds(218, 59, 166, 42);
        add(txtIDReserva);
        
        RSButtonShape btnshpBuscar = new RSButtonShape();
        btnshpBuscar.setText("   BUSCAR");
        btnshpBuscar.setHorizontalAlignment(SwingConstants.CENTER);
        btnshpBuscar.setForma(RSButtonShape.FORMA.ROUND);
        btnshpBuscar.setForegroundText(Color.WHITE);
        btnshpBuscar.setForegroundHover(Color.WHITE);
        btnshpBuscar.setForeground(Color.GRAY);
        btnshpBuscar.setFont(new Font("Dubai", Font.BOLD, 13));
        btnshpBuscar.backgroundHover = SystemColor.controlShadow;
        btnshpBuscar.setBackgroundHover(SystemColor.controlShadow);
        btnshpBuscar.setBackground(new Color(0, 51, 102));
        btnshpBuscar.setIcon(FontIcon.of(FontAwesomeSolid.SEARCH, 25, Color.white));
        btnshpBuscar.setBounds(409, 63, 147, 37);
        add(btnshpBuscar);
        
        RSComboBox comboBox = new RSComboBox();
        comboBox.setModel(new DefaultComboBoxModel(new String[] {"DEBITO", "CREDITO", "TRANSFERENCIA"}));
        comboBox.setColorBorde(new Color(3, 33, 57));
        comboBox.setConBorde(true);
        comboBox.setFont(new Font("Dubai", Font.BOLD, 16));
        comboBox.setForeground(new Color(25, 25, 112));
        comboBox.setColorFondo(new Color(255, 255, 255));
        comboBox.setColorSeleccion(new Color(25, 25, 112));
        comboBox.setColorArrow(new Color(25, 25, 112));
        comboBox.setBounds(218, 111, 166, 32);
        add(comboBox);
        
        RSTextFieldOne txtMonto = new RSTextFieldOne();
        txtMonto.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
              char c = e.getKeyChar();
              if (!((c >= '0') && (c <= '9') ||
                 (c == KeyEvent.VK_BACK_SPACE) ||
                 (c == KeyEvent.VK_DELETE))) {
                getToolkit().beep();
                e.consume();
              }
              boolean max = txtMonto.getText().length() >= 9;
              if ( max ){
                  e.consume();
              }   
            }
          });
        txtMonto.setPlaceholder("");
        txtMonto.setPhColor(SystemColor.controlDkShadow);
        txtMonto.setForeground(new Color(25, 25, 112));
        txtMonto.setFont(new Font("Dubai", Font.BOLD, 20));
        txtMonto.setBorderColor(new Color(3, 33, 57));
        txtMonto.setBounds(218, 159, 166, 42);
        add(txtMonto);
        
        RSTextFieldOne txtTransac = new RSTextFieldOne();
        txtTransac.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
              char c = e.getKeyChar();
              if (!((c >= '0') && (c <= '9') ||
                 (c == KeyEvent.VK_BACK_SPACE) ||
                 (c == KeyEvent.VK_DELETE))) {
                getToolkit().beep();
                e.consume();
              }
              boolean max = txtTransac.getText().length() >= 9;
              if ( max ){
                  e.consume();
              }   
            }
          });
        txtTransac.setPlaceholder("");
        txtTransac.setPhColor(SystemColor.controlDkShadow);
        txtTransac.setForeground(new Color(25, 25, 112));
        txtTransac.setFont(new Font("Dubai", Font.BOLD, 20));
        txtTransac.setBorderColor(new Color(3, 33, 57));
        txtTransac.setBounds(218, 212, 166, 42);
        add(txtTransac);
    }// </editor-fold>//GEN-END:initComponents
    private javax.swing.JLabel jLabel1;
    
    class UppercaseDocumentFilter extends DocumentFilter {
        public void insertString(DocumentFilter.FilterBypass fb, int offset,
                String text, AttributeSet attr) throws BadLocationException {

            fb.insertString(offset, text.toUpperCase(), attr);
        }

        public void replace(DocumentFilter.FilterBypass fb, int offset, int length,
                String text, AttributeSet attrs) throws BadLocationException {

            fb.replace(offset, length, text.toUpperCase(), attrs);
        }
    }
}
