/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;
import javax.swing.SwingConstants;

import org.kordamp.ikonli.entypo.Entypo;
import org.kordamp.ikonli.fontawesome5.FontAwesomeSolid;
import org.kordamp.ikonli.swing.FontIcon;

import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import RSMaterialComponent.RSButtonIconOne;
import rojeru_san.efectos.ValoresEnum.ICONS;
import RSMaterialComponent.RSButtonIconTwo;

import java.awt.Color;
import java.awt.Font;
import necesario.Global.THEMETOOLTIP;
import RSMaterialComponent.RSButtonShapeIcon;
import RSMaterialComponent.RSButtonShapeIcon.FORMA;
import Vista.MainMenu;
import RSMaterialComponent.RSButtonShape;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import RSMaterialComponent.RSTextFieldTwo;
import newscomponents.RSDateChooser;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import RSMaterialComponent.RSTextFieldOne;
import java.awt.SystemColor;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import rojeru_san.complementos.RSCustomPopuMenu;
import RSMaterialComponent.RSComboBox;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JSeparator;
import javax.swing.JList;
import javax.swing.AbstractListModel;
import javax.swing.border.LineBorder;

/**
 *
 * @author RavenPC
 */
public class RegistroReserva extends javax.swing.JPanel {

	private static final String EMAIL_PATTERN = 
		    "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
		    + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";

	DocumentFilter filter = new UppercaseDocumentFilter();
	
    /**
     * Creates new form Panel1
     */
    public RegistroReserva() {
    	setBackground(new Color(255, 255, 255));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel1.setBounds(0, 0, 785, 37);
        jLabel1.setForeground(new Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(SwingConstants.CENTER);

        jLabel1.setBackground(new Color(0, 80, 112));
        jLabel1.setFont(new Font("Dubai", Font.BOLD, 20)); // NOI18N
        jLabel1.setText("Crear una Reserva");
        jLabel1.setOpaque(true);
        
        RSButtonShape btnshpAgregarCliente = new RSButtonShape();
        btnshpAgregarCliente.addActionListener(new ActionListener() {
        	@Override
        	public void actionPerformed(ActionEvent e) {
        		JOptionPane.showMessageDialog(null, "EL CLIENTE FUE GUARDADO EXITOSAMENTE", "MENSAJE", JOptionPane.INFORMATION_MESSAGE);      	
        		//MensajeOK mensaje = new MensajeOK("GUARDAR CLIENTE", "EL CLIENTE FUE GUARDADO EXITOSAMENTE");
        		//mensaje.setVisible(true);
            	MainMenu.panelBody.removeAll();
            	MainMenu.panelBody.add(new MenuClientes());
            	MainMenu.panelBody.repaint();
            	MainMenu.panelBody.revalidate();
        	
        	}
        });
        btnshpAgregarCliente.setBounds(298, 569, 211, 63);
        btnshpAgregarCliente.setFont(new Font("Dubai", Font.BOLD, 13));
        btnshpAgregarCliente.setForegroundHover(Color.white);
        btnshpAgregarCliente.backgroundHover = UIManager.getColor("Button.shadow");
        btnshpAgregarCliente.setBackgroundHover(new Color(3, 33, 57));
        btnshpAgregarCliente.setForegroundText(Color.white);
        btnshpAgregarCliente.setForeground(Color.gray);
        btnshpAgregarCliente.setBackground(new Color(0, 51, 102));
        btnshpAgregarCliente.setHorizontalAlignment(SwingConstants.CENTER);
        btnshpAgregarCliente.setText("   GUARDAR");
        btnshpAgregarCliente.setIcon(FontIcon.of(FontAwesomeSolid.SAVE, 40, Color.white));
        btnshpAgregarCliente.setForma(RSButtonShape.FORMA.ROUND);
        
        RSButtonShape btnshpBuscarCliente = new RSButtonShape();
        btnshpBuscarCliente.addActionListener(new ActionListener() {
        	@Override
        	public void actionPerformed(ActionEvent e) {
            	MainMenu.panelBody.removeAll();
            	MainMenu.panelBody.add(new MenuClientes());
            	MainMenu.panelBody.repaint();
            	MainMenu.panelBody.revalidate();
        	}
        });
        btnshpBuscarCliente.setBounds(523, 569, 211, 63);
        btnshpBuscarCliente.setFont(new Font("Dubai", Font.BOLD, 13));
        btnshpBuscarCliente.setForegroundHover(new Color(3, 33, 57));
        btnshpBuscarCliente.setBackgroundHover(new Color(128, 128, 128));
        btnshpBuscarCliente.setForegroundText(new Color(3, 33, 57));
        btnshpBuscarCliente.setForeground(new Color(0, 128, 128));
        btnshpBuscarCliente.setBackground(new Color(211, 211, 211));
        btnshpBuscarCliente.setText("   CANCELAR");
        btnshpBuscarCliente.setHorizontalAlignment(SwingConstants.CENTER);
        btnshpBuscarCliente.setIcon(FontIcon.of(Entypo.BLOCK, 40, new Color(0, 51, 102)));
        btnshpBuscarCliente.setForma(RSButtonShape.FORMA.ROUND);
        
        JLabel lblRUT = new JLabel("Buscar Propiedad:");
        lblRUT.setForeground(new Color(3, 33,  57));
        lblRUT.setBounds(34, 96, 178, 33);
        lblRUT.setHorizontalAlignment(SwingConstants.RIGHT);
        lblRUT.setFont(new Font("Dubai", Font.BOLD, 20));
        
        JLabel lblNombre = new JLabel("Nombre de la Propiedad:");
        lblNombre.setForeground(new Color(3, 33,  57));
        lblNombre.setBounds(26, 150, 230, 33);
        lblNombre.setHorizontalAlignment(SwingConstants.RIGHT);
        lblNombre.setFont(new Font("Dubai", Font.BOLD, 20));
        setLayout(null);
        add(jLabel1);
        add(btnshpAgregarCliente);
        add(btnshpBuscarCliente);
        add(lblRUT);
        add(lblNombre);
        
        JLabel lblApellidoAterno = new JLabel("Cantidad de Ocupantes:");
        lblApellidoAterno.setForeground(new Color(3, 33,  57));
        lblApellidoAterno.setHorizontalAlignment(SwingConstants.RIGHT);
        lblApellidoAterno.setFont(new Font("Dubai", Font.BOLD, 20));
        lblApellidoAterno.setBounds(26, 322, 211, 33);
        add(lblApellidoAterno);
        
        JLabel lblFechaDeNacimiento = new JLabel("Fecha de Entrada:");
        lblFechaDeNacimiento.setForeground(new Color(3, 33,  57));
        lblFechaDeNacimiento.setHorizontalAlignment(SwingConstants.RIGHT);
        lblFechaDeNacimiento.setFont(new Font("Dubai", Font.BOLD, 20));
        lblFechaDeNacimiento.setBounds(51, 366, 186, 33);
        add(lblFechaDeNacimiento);
        
        RSDateChooser dateChooser = new RSDateChooser();
        dateChooser.setBgColor(new Color(3, 33, 57));
        dateChooser.setBackground(new Color(3, 33, 57));
        dateChooser.setFormatDate("dd/MM/yyyy");
        dateChooser.setBounds(252, 366, 166, 42);
        add(dateChooser);
        
        JLabel lblTelfono = new JLabel("Monto de Abono:");
        lblTelfono.setForeground(new Color(3, 33,  57));
        lblTelfono.setHorizontalAlignment(SwingConstants.RIGHT);
        lblTelfono.setFont(new Font("Dubai", Font.BOLD, 20));
        lblTelfono.setBounds(51, 482, 186, 33);
        add(lblTelfono);
        
        RSTextFieldOne txtRUT = new RSTextFieldOne();
        txtRUT.setBorderColor(new Color(3, 33,  57));
        txtRUT.setFont(new Font("Dubai", Font.BOLD, 20));
        txtRUT.setPlaceholder("0001");
        txtRUT.setPhColor(new Color(105, 105, 105));
        txtRUT.setForeground(new Color(25, 25, 112));
        txtRUT.setBounds(227, 92, 140, 42);
        ((AbstractDocument) txtRUT.getDocument()).setDocumentFilter(filter);
        add(txtRUT);
        
        RSTextFieldOne txtTelefono = new RSTextFieldOne();
        txtTelefono.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
              char c = e.getKeyChar();
              if (!((c >= '0') && (c <= '9') ||
                 (c == KeyEvent.VK_BACK_SPACE) ||
                 (c == KeyEvent.VK_DELETE))) {
                getToolkit().beep();
                e.consume();
              }
              boolean max = txtTelefono.getText().length() >= 9;
              if ( max ){
                  e.consume();
              }   
            }
          });
        txtTelefono.setPlaceholder("988776655");
        txtTelefono.setPhColor(SystemColor.controlDkShadow);
        txtTelefono.setForeground(new Color(25, 25, 112));
        txtTelefono.setFont(new Font("Dubai", Font.BOLD, 20));
        txtTelefono.setBorderColor(new Color(3, 33, 57));
        txtTelefono.setBounds(252, 478, 140, 42);
        add(txtTelefono);
        
        JLabel lblFechaDeSalida = new JLabel("Fecha de Salida:");
        lblFechaDeSalida.setHorizontalAlignment(SwingConstants.RIGHT);
        lblFechaDeSalida.setForeground(new Color(3, 33, 57));
        lblFechaDeSalida.setFont(new Font("Dubai", Font.BOLD, 20));
        lblFechaDeSalida.setBounds(51, 425, 186, 33);
        add(lblFechaDeSalida);
        
        RSDateChooser dateChooser_1 = new RSDateChooser();
        dateChooser_1.setFormatDate("dd/MM/yyyy");
        dateChooser_1.setBgColor(new Color(3, 33, 57));
        dateChooser_1.setBackground(new Color(3, 33, 57));
        dateChooser_1.setBounds(252, 423, 166, 42);
        add(dateChooser_1);
        
        RSComboBox comboBox = new RSComboBox();
        comboBox.setFont(new Font("Dubai", Font.BOLD, 16));
        comboBox.setColorBorde(new Color(25, 25, 112));
        comboBox.setConBorde(true);
        comboBox.setForeground(new Color(25, 25, 112));
        comboBox.setColorFondo(new Color(255, 255, 255));
        comboBox.setColorArrow(new Color(25, 25, 112));
        comboBox.setModel(new DefaultComboBoxModel(new String[] {"1", "2", "3", "4", "5"}));
        comboBox.setBounds(251, 323, 70, 32);
        add(comboBox);
        
        RSButtonShape btnshpExplorar = new RSButtonShape();
        btnshpExplorar.setText("   EXPLORAR");
        btnshpExplorar.setHorizontalAlignment(SwingConstants.CENTER);
        btnshpExplorar.setForma(RSButtonShape.FORMA.ROUND);
        btnshpExplorar.setForegroundText(Color.WHITE);
        btnshpExplorar.setForegroundHover(Color.WHITE);
        btnshpExplorar.setForeground(Color.GRAY);
        btnshpExplorar.setFont(new Font("Dubai", Font.BOLD, 13));
        btnshpExplorar.backgroundHover = SystemColor.controlShadow;
        btnshpExplorar.setBackgroundHover(SystemColor.controlShadow);
        btnshpExplorar.setBackground(new Color(0, 51, 102));
        btnshpExplorar.setBounds(385, 94, 123, 37);
        add(btnshpExplorar);
        
        JList list = new JList();
        list.setBorder(new LineBorder(new Color(25, 25, 112), 4));
        list.setFont(new Font("Dubai", Font.BOLD, 14));
        list.setModel(new AbstractListModel() {
        	String[] values = new String[] {"TRANSPORTE DE RECOGIDA", "TOUR A LAS TORRES DEL PAINE"};
        	public int getSize() {
        		return values.length;
        	}
        	public Object getElementAt(int index) {
        		return values[index];
        	}
        });
        list.setBounds(485, 350, 249, 170);
        add(list);
        
        JLabel lblServiciosExtra = new JLabel("Servicios Extra:");
        lblServiciosExtra.setHorizontalAlignment(SwingConstants.LEFT);
        lblServiciosExtra.setForeground(new Color(3, 33, 57));
        lblServiciosExtra.setFont(new Font("Dubai", Font.BOLD, 20));
        lblServiciosExtra.setBounds(485, 310, 140, 33);
        add(lblServiciosExtra);
        
        RSButtonShape btnshpAgregar = new RSButtonShape();
        btnshpAgregar.setText("   AGREGAR");
        btnshpAgregar.setHorizontalAlignment(SwingConstants.CENTER);
        btnshpAgregar.setForma(RSButtonShape.FORMA.ROUND);
        btnshpAgregar.setForegroundText(Color.WHITE);
        btnshpAgregar.setForegroundHover(Color.WHITE);
        btnshpAgregar.setForeground(Color.GRAY);
        btnshpAgregar.setFont(new Font("Dubai", Font.BOLD, 11));
        btnshpAgregar.backgroundHover = SystemColor.controlShadow;
        btnshpAgregar.setBackgroundHover(SystemColor.controlShadow);
        btnshpAgregar.setBackground(new Color(0, 51, 102));
        btnshpAgregar.setBounds(635, 310, 95, 33);
        add(btnshpAgregar);
        
        JLabel lblValorPorNoche = new JLabel("Valor por Noche:");
        lblValorPorNoche.setHorizontalAlignment(SwingConstants.RIGHT);
        lblValorPorNoche.setForeground(new Color(3, 33, 57));
        lblValorPorNoche.setFont(new Font("Dubai", Font.BOLD, 20));
        lblValorPorNoche.setBounds(26, 194, 230, 33);
        add(lblValorPorNoche);
        
        JLabel lblCasaEnEl = new JLabel("Casa en el Fin del Mundo");
        lblCasaEnEl.setHorizontalAlignment(SwingConstants.LEFT);
        lblCasaEnEl.setForeground(new Color(3, 33, 57));
        lblCasaEnEl.setFont(new Font("Dubai", Font.BOLD, 20));
        lblCasaEnEl.setBounds(266, 150, 242, 33);
        add(lblCasaEnEl);
        
        JLabel label = new JLabel("$ 65.000");
        label.setHorizontalAlignment(SwingConstants.LEFT);
        label.setForeground(new Color(3, 33, 57));
        label.setFont(new Font("Dubai", Font.BOLD, 20));
        label.setBounds(266, 194, 242, 33);
        add(label);
        
        JLabel lblDetalleDeLa_1 = new JLabel();
        lblDetalleDeLa_1.setText("DETALLE DE LA PROPIEDAD");
        lblDetalleDeLa_1.setOpaque(true);
        lblDetalleDeLa_1.setHorizontalAlignment(SwingConstants.CENTER);
        lblDetalleDeLa_1.setForeground(Color.WHITE);
        lblDetalleDeLa_1.setFont(new Font("Dubai", Font.BOLD, 16));
        lblDetalleDeLa_1.setBackground(new Color(0, 128, 128));
        lblDetalleDeLa_1.setBounds(0, 48, 785, 28);
        add(lblDetalleDeLa_1);
        
        JLabel lblDetalleDeLa = new JLabel();
        lblDetalleDeLa.setText("DETALLE DE LA RESERVA");
        lblDetalleDeLa.setOpaque(true);
        lblDetalleDeLa.setHorizontalAlignment(SwingConstants.CENTER);
        lblDetalleDeLa.setForeground(Color.WHITE);
        lblDetalleDeLa.setFont(new Font("Dubai", Font.BOLD, 16));
        lblDetalleDeLa.setBackground(new Color(0, 128, 128));
        lblDetalleDeLa.setBounds(0, 253, 785, 28);
        add(lblDetalleDeLa);
    }// </editor-fold>//GEN-END:initComponents
    private javax.swing.JLabel jLabel1;
    
    class UppercaseDocumentFilter extends DocumentFilter {
        public void insertString(DocumentFilter.FilterBypass fb, int offset,
                String text, AttributeSet attr) throws BadLocationException {

            fb.insertString(offset, text.toUpperCase(), attr);
        }

        public void replace(DocumentFilter.FilterBypass fb, int offset, int length,
                String text, AttributeSet attrs) throws BadLocationException {

            fb.replace(offset, length, text.toUpperCase(), attrs);
        }
    }
}
